trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastructure/*

parameters:
- name: environments
  type: object
  default:
    - test
    - prod

variables:
  azureSubscription: 'Your-Azure-Service-Connection'

stages:
- ${{ each env in parameters.environments }}:
  - stage: Deploy_${{ env }}
    displayName: 'Deploy to ${{ env }}'
    jobs:
    - deployment: Deploy_Infrastructure
      displayName: 'Deploy Infrastructure'
      environment: ${{ env }}
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureCLI@2
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create \
                    --resource-group $(resourceGroup) \
                    --template-file infrastructure/main.bicep \
                    --parameters environmentName=${{ env }}